#!/usr/bin/env bash
#Configuring web-01 to have a response which is HTTP header

sudo apt-get update
sudo apt-get install -y nginx

# Creating an index page
echo "Hello World!" | sudo tee /var/www/html/index.html

# Performing a redirection
string_for_replacement="server_name _;\n\trewrite ^\/redirect_me https:\/\/github.com\/elburhan permanent;"

sudo sed -i "s/server_name _;/$string_for_replacement" /etc/nginx/sites-enabled/default

echo "Ceci n'est pas une page" | sudo tee /var/www/html/404.html

#Custom HTTP response header

sudo sed -i "server_name _;/a add_header X-Served-By $HOSTNAME;" /etc/nginx/sites-enabled/default

#Testing for syntax error

sudo nginx -t

#Restarting nginx
sudo service nginx restart
