#!/usr/bin/env bash
# This script groups visitors by IP and HTTP status code and displays the data.

# Parse Apache log file, extract IP and HTTP status code, and count occurrences
awk '{print $1, $9}' $1 | sort | uniq -c | sort -nr | awk '{print $2, $3, $1}'
