#!/usr/bin/env bash
# This script displays the time for 12 hours and 59 minutes

hour=0
minute=1

while [ $hour -le 12 ]; do
    while [ $minute -le 59 ]; do
        printf "%02d:%02d\n" $hour $minute
        ((minute++))
    done
    ((hour++))
    minute=1
done
